### ISSUE TITLE
java.lang.RuntimeException: InputChannel is not initialized.

### ISSUE THREAD

**Issue by kasnder** [OxfordHCC/tracker-control-android#10]
There seem to be a weird error within the leading, sometimes leading to the following crashing with the error message:

`java.lang.RuntimeException: InputChannel is not initialized.
at android.view.InputEventReceiver.nativeInit(Native Method)
at android.view.InputEventReceiver.<init>(InputEventReceiver.java:71)
at android.view.ViewRootImpl$WindowInputEventReceiver.<init>(ViewRootImpl.java:7605)
at android.view.ViewRootImpl.setView(ViewRootImpl.java:956)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4296)
at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

This issue is known by Google, but has no fix, see [here](https://issuetracker.google.com/issues/37018931). Device restart [might help](https://stackoverflow.com/questions/34039657/what-might-be-the-reason-for-this-exception-java-lang-runtimeexception-inputch).

**Comment by kasnder** [comment]
Closed for now.
