### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Civilian-No-001** [OxfordHCC/tracker-control-android#197]
Android 11
Sony Xperia 1 
2021.05.05 fdroid

Occurs when clicking app icon to view the tracker, all crashes occur in same app.

`FATAL EXCEPTION: AsyncTask #2
Process: net.kollnig.missioncontrol.fdroid, PID: 10698
lanchon.multidexlib2.DuplicateTypeException: Lcom/example/helloworld/BuildConfig;
	at lanchon.multidexlib2.MultiDexContainerBackedDexFile.<init>(MultiDexContainerBackedDexFile.java:42)
	at lanchon.multidexlib2.MultiDexIO.readDexFile(MultiDexIO.java:34)
	at net.kollnig.missioncontrol.Common.detectTrackersStatic(Common.java:172)
	at net.kollnig.missioncontrol.details.TrackersListAdapter.lambda$onCreateViewHolder$2$TrackersListAdapter(TrackersListAdapter.java:130)
	at net.kollnig.missioncontrol.details.-$$Lambda$TrackersListAdapter$ErCdEgWHt08DLGibzfDJHjIhDBA.run(Unknown Source:12)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)`

**Comment by Civilian-No-001** [comment]
`FATAL EXCEPTION: main
Process: net.kollnig.missioncontrol.fdroid, PID: 27975
java.lang.RuntimeException: Unable to instantiate application eu.faircode.netguard.ApplicationEx: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1249)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6714)
	at android.app.ActivityThread.access$1300(ActivityThread.java:242)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1918)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:368)
	at android.app.ActivityThread.main(ActivityThread.java:7710)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user is unlocked
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:494)
	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:479)
	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:188)
	at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:545)
	at org.acra.prefs.SharedPreferencesFactory.create(SharedPreferencesFactory.java:76)
	at org.acra.ACRA.init(ACRA.java:222)
	at org.acra.ACRA.init(ACRA.java:160)
	at org.acra.ACRA.init(ACRA.java:144)
	at org.acra.ACRA.init(ACRA.java:127)
	at eu.faircode.netguard.ApplicationEx.attachBaseContext(ApplicationEx.java:68)
	at android.app.Application.attach(Application.java:351)
	at android.app.Instrumentation.newApplication(Instrumentation.java:1160)
	at android.app.LoadedApk.makeApplication(LoadedApk.java:1241)
	... 9 more`

**Comment by Civilian-No-001** [comment]
`FATAL EXCEPTION: AsyncTask #1
Process: net.kollnig.missioncontrol.fdroid, PID: 6342
lanchon.multidexlib2.DuplicateTypeException: Lcom/example/helloworld/BuildConfig;
	at lanchon.multidexlib2.MultiDexContainerBackedDexFile.<init>(MultiDexContainerBackedDexFile.java:42)
	at lanchon.multidexlib2.MultiDexIO.readDexFile(MultiDexIO.java:34)
	at net.kollnig.missioncontrol.Common.detectTrackersStatic(Common.java:172)
	at net.kollnig.missioncontrol.details.TrackersListAdapter.lambda$onCreateViewHolder$2$TrackersListAdapter(TrackersListAdapter.java:130)
	at net.kollnig.missioncontrol.details.-$$Lambda$TrackersListAdapter$ErCdEgWHt08DLGibzfDJHjIhDBA.run(Unknown Source:12)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)`

**Comment by kasnder** [comment]
Thanks! I've fixed this issue now, and the update can be downloaded from GitHub already, and in a week on F-Droid.

**Comment by Civilian-No-001** [comment]
OH, look fdroid makes us time difference, thanks, I will close this issue.

**Comment by kasnder** [comment]
I'll leave this open since I haven't seen the second error before and need to investigate

**Comment by kasnder** [comment]
Fixed now!
